export const playersDB: Record<string, any> = {
  "1": {
    id: "1",
    name: "Ernesto Guivens",
    pos: "Gardien de but",
    num: 1,
    img: "/players/Ernesto Guivens.jpg",
    filter: "none",
    dob: "12 Mai 2009",
    category: "Équipe Première",
    height: "1.82m",
    weight: "72kg",
    matches: 12,
    goals: 0,
    assists: 0,
    stat2lbl: "Arrêts",
    stat2val: 45,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "8.2",
      minutes: 90
    },
    honours1: 2,
    honours2: 1
  },
  "2": {
    id: "2",
    name: "Serdgy Leandre",
    pos: "Arrière Droit",
    num: 2,
    img: "/players/Serdgy Leandre.jpg",
    filter: "none",
    dob: "05 Avril 2009",
    category: "Équipe Première",
    height: "1.74m",
    weight: "65kg",
    matches: 14,
    goals: 1,
    assists: 3,
    stat2lbl: "Tacles",
    stat2val: 28,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "7.8",
      minutes: 90
    },
    honours1: 1,
    honours2: 1
  },
  "3": {
    id: "3",
    name: "Steevenson Thermidor",
    pos: "Arrière Gauche",
    num: 3,
    img: "/players/Steevenson Thermidor.jpg",
    filter: "none",
    dob: "18 Novembre 2009",
    category: "Équipe Première",
    height: "1.71m",
    weight: "62kg",
    matches: 13,
    goals: 0,
    assists: 4,
    stat2lbl: "Tacles",
    stat2val: 22,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "7.5",
      minutes: 90
    },
    honours1: 1,
    honours2: 1
  },
  "4": {
    id: "4",
    name: "Josue Derat",
    pos: "Défenseur Central",
    num: 4,
    img: "/players/Josue Derat.jpg",
    filter: "none",
    dob: "22 Février 2009",
    category: "Équipe Première",
    height: "1.85m",
    weight: "78kg",
    matches: 15,
    goals: 2,
    assists: 1,
    stat2lbl: "Tacles",
    stat2val: 35,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "8.5",
      minutes: 90
    },
    honours1: 2,
    honours2: 1
  },
  "5": {
    id: "5",
    name: "Maxo Pierre",
    pos: "Défenseur Central",
    num: 5,
    img: "/players/Maxo Pierre.jpg",
    filter: "none",
    dob: "10 Septembre 2009",
    category: "U17",
    height: "1.80m",
    weight: "75kg",
    matches: 14,
    goals: 1,
    assists: 0,
    stat2lbl: "Tacles",
    stat2val: 31,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "7.9",
      minutes: 90
    },
    honours1: 1,
    honours2: 1
  },
  "6": {
    id: "6",
    name: "Marc-Hero Clerissier",
    pos: "Milieu Central",
    num: 6,
    img: "/players/Marc-Hero Clerissier.jpg",
    filter: "none",
    dob: "14 Janvier 2009",
    category: "U17",
    height: "1.76m",
    weight: "68kg",
    matches: 15,
    goals: 3,
    assists: 5,
    stat2lbl: "Buts",
    stat2val: 3,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "8.0",
      minutes: 85
    },
    honours1: 2,
    honours2: 2
  },
  "7": {
    id: "7",
    name: "Rivaldo Sanon",
    pos: "Ailier Gauche",
    num: 7,
    img: "/players/Rivaldo Sanon.jpg",
    filter: "none",
    dob: "30 Juin 2009",
    category: "U17",
    height: "1.73m",
    weight: "64kg",
    matches: 14,
    goals: 8,
    assists: 6,
    stat2lbl: "Buts",
    stat2val: 8,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "9.0",
      minutes: 90
    },
    honours1: 2,
    honours2: 1
  },
  "8": {
    id: "8",
    name: "Smarthinly Berry",
    pos: "Milieu Défensif",
    num: 8,
    img: "/players/Smarthinly Berry.jpg",
    filter: "none",
    dob: "02 Juillet 2009",
    category: "U17",
    height: "1.78m",
    weight: "70kg",
    matches: 13,
    goals: 1,
    assists: 2,
    stat2lbl: "Tacles",
    stat2val: 26,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "7.6",
      minutes: 90
    },
    honours1: 1,
    honours2: 1
  },
  "9": {
    id: "9",
    name: "Jameslay Nelson",
    pos: "Avant-Centre",
    num: 9,
    img: "/players/Jameslay Nelson.jpg",
    filter: "none",
    dob: "11 Décembre 2009",
    category: "U15",
    height: "1.81m",
    weight: "74kg",
    matches: 15,
    goals: 12,
    assists: 4,
    stat2lbl: "Buts",
    stat2val: 12,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "8.8",
      minutes: 90
    },
    honours1: 2,
    honours2: 2
  },
  "10": {
    id: "10",
    name: "Wilbensly Laforsse",
    pos: "Milieu Offensif",
    num: 10,
    img: "/players/Wilbensly Laforsse.jpg",
    filter: "none",
    dob: "25 Août 2009",
    category: "U15",
    height: "1.72m",
    weight: "63kg",
    matches: 14,
    goals: 5,
    assists: 8,
    stat2lbl: "Buts",
    stat2val: 5,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "8.4",
      minutes: 75
    },
    honours1: 2,
    honours2: 1
  },
  "11": {
    id: "11",
    name: "Messi Frederic",
    pos: "Ailier Droit",
    num: 11,
    img: "/players/Messi Frederic.jpg",
    filter: "none",
    dob: "24 Octobre 2009",
    category: "U15",
    height: "1.69m",
    weight: "59kg",
    matches: 15,
    goals: 10,
    assists: 7,
    stat2lbl: "Buts",
    stat2val: 10,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "9.2",
      minutes: 90
    },
    honours1: 2,
    honours2: 2
  },
  "12": {
    id: "12",
    name: "Vladimir Loppe",
    pos: "Défenseur Central",
    num: 12,
    img: "/players/Vladimir Loppe.jpg",
    filter: "none",
    dob: "03 Mars 2009",
    category: "U15",
    height: "1.79m",
    weight: "73kg",
    matches: 11,
    goals: 0,
    assists: 1,
    stat2lbl: "Tacles",
    stat2val: 18,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "7.2",
      minutes: 60
    },
    honours1: 1,
    honours2: 0
  },
  "14": {
    id: "14",
    name: "Wildens Joseph",
    pos: "Milieu Central",
    num: 14,
    img: "/players/Wildens Joseph.jpg",
    filter: "none",
    dob: "17 Juillet 2009",
    category: "U13",
    height: "1.75m",
    weight: "67kg",
    matches: 12,
    goals: 2,
    assists: 2,
    stat2lbl: "Buts",
    stat2val: 2,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "7.4",
      minutes: 70
    },
    honours1: 1,
    honours2: 1
  },
  "15": {
    id: "15",
    name: "Widley Fleurius",
    pos: "Milieu Central",
    num: 15,
    img: "/players/Widley Fleurius.jpg",
    filter: "none",
    dob: "09 Mai 2009",
    category: "U13",
    height: "1.77m",
    weight: "69kg",
    matches: 13,
    goals: 1,
    assists: 4,
    stat2lbl: "Buts",
    stat2val: 1,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "7.7",
      minutes: 80
    },
    honours1: 1,
    honours2: 1
  },
  "16": {
    id: "16",
    name: "Teddy Alexandre",
    pos: "Gardien de but",
    num: 16,
    img: "/players/Teddy Alexandre.jpg",
    filter: "none",
    dob: "28 Janvier 2009",
    category: "U13",
    height: "1.84m",
    weight: "76kg",
    matches: 4,
    goals: 0,
    assists: 0,
    stat2lbl: "Arrêts",
    stat2val: 12,
    recentMatch: {
      opponent: "AS Delmas",
      result: "Victoire 2-1",
      rating: "7.5",
      minutes: 90
    },
    honours1: 1,
    honours2: 0
  }
};
