-- SCRIPT DE CRÉATION DES TABLES POUR SUPABASE (A EXECUTER DANS LE SQL EDITOR DE SUPABASE)

-- 1. Table actualités (news)
CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cat VARCHAR(100) NOT NULL,
  date VARCHAR(100) NOT NULL,
  title TEXT NOT NULL,
  desc_text TEXT NOT NULL,
  img TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table joueurs (players)
CREATE TABLE IF NOT EXISTS players (
  id VARCHAR(100) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  pos VARCHAR(100) NOT NULL,
  num INT NOT NULL,
  img TEXT NOT NULL,
  detail_img TEXT,
  filter VARCHAR(100) DEFAULT 'none',
  dob VARCHAR(100) DEFAULT '',
  category VARCHAR(100) NOT NULL,
  height VARCHAR(100),
  weight VARCHAR(100),
  matches INT DEFAULT 0,
  goals INT DEFAULT 0,
  assists INT DEFAULT 0,
  stat2lbl VARCHAR(100) DEFAULT 'Buts',
  stat2val INT DEFAULT 0,
  pob VARCHAR(255) DEFAULT 'Port-au-Prince, Haïti',
  foot VARCHAR(50) DEFAULT 'Droit',
  nationality VARCHAR(100) DEFAULT 'Haïtienne',
  bio TEXT,
  honours1 INT DEFAULT 1,
  honours2 INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Mettre à jour les colonnes si la table existait déjà dans Supabase
ALTER TABLE players ADD COLUMN IF NOT EXISTS detail_img TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS filter VARCHAR(100) DEFAULT 'none';
ALTER TABLE players ADD COLUMN IF NOT EXISTS dob VARCHAR(100) DEFAULT '';
ALTER TABLE players ADD COLUMN IF NOT EXISTS height VARCHAR(100);
ALTER TABLE players ADD COLUMN IF NOT EXISTS weight VARCHAR(100);
ALTER TABLE players ADD COLUMN IF NOT EXISTS matches INT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS goals INT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS assists INT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS stat2lbl VARCHAR(100) DEFAULT 'Buts';
ALTER TABLE players ADD COLUMN IF NOT EXISTS stat2val INT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS pob VARCHAR(255) DEFAULT 'Port-au-Prince, Haïti';
ALTER TABLE players ADD COLUMN IF NOT EXISTS foot VARCHAR(50) DEFAULT 'Droit';
ALTER TABLE players ADD COLUMN IF NOT EXISTS nationality VARCHAR(100) DEFAULT 'Haïtienne';
ALTER TABLE players ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS honours1 INT DEFAULT 1;
ALTER TABLE players ADD COLUMN IF NOT EXISTS honours2 INT DEFAULT 0;

-- 3. Table des images du slider (slides)
CREATE TABLE IF NOT EXISTS slides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Table inscriptions aux stages (stages_inscriptions)
CREATE TABLE IF NOT EXISTS stages_inscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL,
  dob VARCHAR(100) NOT NULL,
  tel VARCHAR(100) NOT NULL,
  stage TEXT NOT NULL,
  note TEXT,
  photo TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table rendez-vous administratifs (appointments)
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_nom VARCHAR(255) NOT NULL,
  enfant_nom VARCHAR(255) NOT NULL,
  tel VARCHAR(100) NOT NULL,
  date VARCHAR(100) NOT NULL,
  heure VARCHAR(100) NOT NULL,
  raison VARCHAR(255) DEFAULT 'Inscription académique',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Table profils supporters (supporters)
CREATE TABLE IF NOT EXISTS supporters (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  notify_news BOOLEAN DEFAULT TRUE,
  notify_match_start BOOLEAN DEFAULT TRUE,
  notify_goals BOOLEAN DEFAULT TRUE,
  notify_half_time BOOLEAN DEFAULT TRUE,
  notify_final_score BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Table des inscriptions complètes (inscriptions)
CREATE TABLE IF NOT EXISTS inscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enfant_nom VARCHAR(255) NOT NULL,
  enfant_prenom VARCHAR(255) NOT NULL,
  enfant_dob VARCHAR(100) NOT NULL,
  parent_nom VARCHAR(255) NOT NULL,
  parent_prenom VARCHAR(255) NOT NULL,
  parent_tel VARCHAR(100) NOT NULL,
  parent_email VARCHAR(255) NOT NULL,
  form_data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- INSERER LES DONNEES INITIALES (EXEMPLES)

-- Insérer les slides par défaut (si non existants)
INSERT INTO slides (url)
SELECT s.url FROM (VALUES
  ('/stadium_hero_1780681869623.png'),
  ('/club_hero.png'),
  ('/kick_hero.png'),
  ('/news_hero.png'),
  ('/trophy_moment_1780681956500.png'),
  ('/soccer.png'),
  ('/universe_bg.png')
) AS s(url)
WHERE NOT EXISTS (SELECT 1 FROM slides WHERE slides.url = s.url);

-- Insérer les actualités par défaut (si non existantes)
INSERT INTO news (cat, date, title, desc_text, img)
SELECT n.cat, n.date, n.title, n.desc_text, n.img FROM (VALUES
  ('Match', 'Il y a 2 heures', 'Le Condor FC décroche une victoire cruciale à l''extérieur', 'Une performance époustouflante en seconde période assure les trois points sur la route.', '/player_action_1_1780681882713.png'),
  ('Transferts', 'Il y a 5 heures', 'Nouvelle recrue officiellement dévoilée à l''Arène', 'Le club renforce sa ligne offensive avec l''arrivée d''un jeune international prometteur.', '/condor_jersey_1780681923538.png')
) AS n(cat, date, title, desc_text, img)
WHERE NOT EXISTS (SELECT 1 FROM news WHERE news.title = n.title);

-- Nettoyer le doublon joueur 71 s'il existe
DELETE FROM players WHERE id = '71';

-- Insérer les 14 joueurs officiels U17 avec leurs 2 photos (affichage et célébration)
INSERT INTO players (id, name, pos, num, img, detail_img, dob, category, matches, goals, assists, stat2lbl, stat2val, pob, foot, nationality, bio, honours1, honours2) VALUES
('1', 'Wilbensly Laforsse', 'Gardien de But', 1, '/players/Wilbensly Laforsse.jpg', '/players/Wilbensly Laforsse_celebration.jpg', '03/10/2008', 'U17', 14, 0, 0, 'Arrêts', 35, 'Haiti', 'Droit', 'Haïtienne', 'Wilbensly Laforsse est un gardien de but qui se distingue par ses réflexes exceptionnels et son influence positive sur son équipe. Portant le maillot numéro 1, il possède une excellente capacité à réaliser des arrêts décisifs grâce à sa rapidité de réaction et sa concentration constante. Droitier, il fait preuve d’un grand leadership sur le terrain, communiquant continuellement avec ses défenseurs afin d’organiser et de guider le bloc défensif. Toujours attentif au déroulement du match, il conserve un haut niveau de concentration du début à la fin, ce qui lui permet d’intervenir avec efficacité dans les moments importants. Passionné par son poste et animé par une forte volonté de progresser, Wilbensly inspire confiance à ses coéquipiers par son calme, sa maturité et sa présence rassurante dans les buts. Son mélange de talent, de détermination et de qualités de leader fait de lui un gardien particulièrement précieux pour son équipe.', 2, 1),
('2', 'Guyvens Ernesto Mexil', 'Milieu de Terrain Défensif', 9, '/players/Guyvens Ernesto Mexil.jpg', '/players/Guyvens Ernesto Mexil_celebration.jpg', '10/12/2008', 'U17', 13, 1, 2, 'Tacles', 26, 'Haiti', 'Gauche', 'Haïtienne', 'Guyvens Ernesto Mexil est un milieu de terrain défensif qui se distingue par son état d’esprit combatif et sa mentalité de guerrier. Portant le maillot numéro 9, il aborde chaque match avec une intensité remarquable et une volonté constante de se battre pour son équipe. Gaucher, il excelle dans les duels grâce à son engagement, sa détermination et sa capacité à imposer sa présence au milieu du terrain. Très performant dans le jeu aérien, il gagne régulièrement ses confrontations grâce à son timing, sa puissance et son sens de l’anticipation. Infatigable dans l’effort, Guyvens apporte de l’énergie, du caractère et de la solidité à son équipe, tout en montrant un esprit de sacrifice exemplaire. Son leadership naturel, sa résilience et son agressivité positive font de lui un joueur précieux capable d’influencer le match par son impact physique et mental.', 1, 1),
('3', 'Marc-Hero Clérisier', 'Ailier Gauche', 47, '/players/Marc-Hero Clerissier.jpg', '/players/Marc-Hero Clerissier_celebration.jpg', '08/12/2008', 'U17', 15, 3, 5, 'Buts', 3, 'Haiti', 'Droit', 'Haïtienne', 'Marc-Hero Clérisier est un ailier gauche qui se distingue par sa vitesse et sa capacité à créer des différences sur son côté. Portant le maillot numéro 47, il utilise son pied droit avec efficacité pour attaquer les espaces et mettre les défenses adverses sous pression. Doté d’une excellente accélération, il est capable de prendre rapidement l’avantage sur son vis-à-vis et de provoquer le danger dans les zones offensives. Ses déplacements dynamiques et sa rapidité d’exécution font de lui une menace constante dans les phases de transition. Marc-Hero se démarque également par la qualité de ses centres, qu’il délivre avec précision pour mettre ses coéquipiers dans les meilleures conditions devant le but. Percutant, énergique et efficace, il apporte de la profondeur et de la créativité au jeu offensif de son équipe.', 2, 2),
('5', 'Messi Frédéric', 'Ailier Gauche', 14, '/players/Messi Frederic.jpg', '/players/Messi Frederic_celebration.jpg', '04/01/2009', 'U17', 15, 10, 7, 'Buts', 10, 'Haïti', 'Droit', 'Haïtienne', 'Messi Frédéric est un ailier gauche qui se distingue par son style de jeu direct et son efficacité dans les phases offensives. Portant le maillot numéro 14, il utilise sa vitesse et sa qualité technique pour créer constamment des différences sur son côté. Droitier, il maîtrise une variété de gestes techniques et de dribbles qui lui permettent d’éliminer ses adversaires tout en restant efficace dans ses prises de décision. En plus de sa capacité à déséquilibrer les défenses, Messi possède une excellente qualité de passe et sait parfaitement mettre ses coéquipiers dans les meilleures conditions. Très généreux dans l’effort, il n’hésite pas à effectuer les replis défensifs pour aider son équipe lorsque nécessaire. Rapide, travailleur et collectif, il est un joueur complet dont l’impact se fait sentir dans toutes les phases du jeu.', 2, 2),
('6', 'Wildens Joseph', 'Défenseur Latéral Droit / Défenseur Central', 8, '/players/Wildens Joseph.jpg', '/players/Wildens Joseph_celebration.jpg', '09/03/2009', 'U17', 12, 2, 2, 'Tacles', 28, 'Haiti', 'Droit', 'Haïtienne', 'Wildens Joseph est un joueur polyvalent capable d’évoluer aussi bien au poste de défenseur latéral droit qu’en défense centrale. Portant le maillot numéro 8, il se distingue par son calme, sa précision et son intelligence dans l’utilisation du ballon. Droitier, il possède une excellente qualité de relance et se montre particulièrement efficace dans le jeu long, trouvant régulièrement ses coéquipiers grâce à des passes précises qui permettent à son équipe de progresser rapidement sur le terrain. Très performant dans les duels aériens, il utilise son timing et sa lecture du jeu pour s’imposer dans les confrontations physiques. Défenseur moderne, Wildens est à l’aise balle au pied et contribue activement à la construction du jeu depuis l’arrière. Sa sérénité sous pression, sa qualité technique et sa solidité défensive font de lui un élément fiable et complet, capable d’apporter autant dans la récupération que dans l’organisation du jeu.', 1, 1),
('8', 'Teddy Alexandre', 'Ailier Droit', 7, '/players/Teddy Alexandre.jpg', '/players/Teddy Alexandre_celebration.jpg', '27/09/2009', 'U17', 15, 4, 3, 'Buts', 4, 'Haiti', 'Gauche', 'Haïtienne', 'Teddy Alexandre est un ailier droit qui se distingue par sa vitesse exceptionnelle et son explosivité dans les phases offensives. Portant le maillot numéro 7, il utilise son puissant pied gauche pour créer constamment du danger sur son côté. Ses accélérations fulgurantes et ses changements de rythme lui permettent de prendre l’avantage sur ses adversaires et de déséquilibrer les défenses avec régularité. Toujours dynamique dans ses déplacements, Teddy est capable de transformer une situation anodine en occasion dangereuse grâce à sa rapidité d’exécution et sa vivacité. Percutant, imprévisible et difficile à contenir dans les espaces, il représente une menace permanente pour les défenses adverses et apporte beaucoup d’intensité au jeu offensif de son équipe.', 2, 1),
('10', 'Steevenson Thermidor', 'Milieu de Terrain Défensif / Défenseur Central', 66, '/players/Steevenson Thermidor.jpg', '/players/Steevenson Thermidor_celebration.jpg', '29/03/2010', 'U17', 13, 0, 4, 'Tacles', 22, 'Haiti', 'Droit', 'Haïtienne', 'Steevenson Thermidor est un joueur polyvalent capable d’évoluer aussi bien au poste de milieu de terrain défensif qu’en défense centrale. Portant le maillot numéro 66, il se distingue par son intelligence de jeu et sa grande qualité technique. Droitier, il possède une excellente précision de passe qui lui permet de dicter le rythme du jeu et de contribuer efficacement à la construction des actions. Sa compréhension tactique lui permet de s’adapter à différents rôles sur le terrain tout en maintenant un haut niveau de performance. Calme dans ses prises de décision et fiable dans l’utilisation du ballon, Steevenson privilégie toujours les choix les plus efficaces pour son équipe. Grâce à sa polyvalence, sa qualité de distribution et sa lecture du jeu, il représente un élément précieux capable d’apporter stabilité et équilibre dans plusieurs secteurs du terrain.', 1, 1),
('11', 'Jameseley Nelson', 'Défenseur Latéral Droit', 3, '/players/Jameseley Nelson.jpg', '/players/Jameseley Nelson_celebration.jpg', '12/09/2009', 'U17', 15, 0, 2, 'Tacles', 31, 'Haiti', 'Droit', 'Haïtienne', 'Jameseley Nelson est un défenseur latéral droit qui se distingue par sa puissance physique et sa solidité défensive. Portant le maillot numéro 3, il impose une grande présence dans les duels grâce à sa force et à son engagement constant. Droitier, il excelle dans les tâches défensives, notamment dans les interceptions et les interventions propres qui permettent de stopper efficacement les actions adverses. Très difficile à déborder, Jameseley fait preuve d’une grande rigueur et d’une concentration constante tout au long des matchs. Son agressivité maîtrisée, sa fiabilité et sa capacité à gagner les duels en font un défenseur sûr et efficace. Grâce à ses qualités défensives et à son impact physique, il constitue un élément essentiel pour stabiliser le côté droit de sa défense.', 2, 2),
('12', 'Rivaldo Sanon', 'Milieu de Terrain Défensif', 6, '/players/Rivaldo Sanon.jpg', '/players/Rivaldo Sanon_celebration.jpg', '14/03/2010', 'U17', 14, 8, 6, 'Tacles', 24, 'Haiti', 'Droit', 'Haïtienne', 'Rivaldo Sanon est un milieu de terrain défensif qui se distingue par son profil extrêmement complet et son intelligence de jeu. Portant le maillot numéro 6, il est capable d’évoluer avec assurance dans les phases de récupération comme dans la construction du jeu. Ambidextre et très à l’aise techniquement, il excelle dans le dribble et se montre particulièrement difficile à presser grâce à sa maîtrise des feintes et son sang-froid sous pression. Droitier de base, il sait adapter son jeu avec les deux pieds, ce qui lui permet de garder un avantage constant dans les situations serrées. Toujours en mouvement et attentif à son environnement, il scanne le jeu en permanence pour prendre les meilleures décisions. Intelligent dans la gestion du rythme, il sait quand jouer rapidement en touches limitées et quand temporiser pour mieux organiser son équipe. Solide physiquement, efficace à la récupération et précis dans ses passes, Rivaldo est un milieu moderne, complet et influent, capable d’avoir un impact majeur dans toutes les phases du jeu.', 2, 1),
('13', 'Smarthinly Luiggy Berry', 'Défenseur Central', 27, '/players/Smarthinly Berry.jpg', '/players/Smarthinly Berry_celebration.jpg', '16/09/2010', 'U17', 13, 1, 2, 'Tacles', 26, 'Massachusetts, États-Unis', 'Droit', 'Américaine', 'Smarthinly Luiggy Berry est un défenseur central qui se distingue par sa qualité technique et son intelligence dans la relance. Portant le maillot numéro 27, il est particulièrement à l’aise avec le ballon et joue un rôle important dans la construction du jeu depuis l’arrière. Droitier, il privilégie la simplicité et l’efficacité, sélectionnant toujours les meilleures options de passe pour maintenir la fluidité du jeu. Sa sérénité sous pression lui permet de résister efficacement au pressing adverse et de conserver le contrôle même dans les situations les plus exigeantes. Calme, précis et confiant balle au pied, Smarthinly possède les qualités d’un défenseur moderne capable d’allier sécurité défensive et contribution offensive dans la première relance.', 1, 1),
('14', 'Maxo Pierre', 'Défenseur Latéral Gauche', 5, '/players/Maxo Pierre.jpg', '/players/Maxo Pierre_celebration.jpg', '27/12/2010', 'U17', 14, 1, 0, 'Tacles', 31, 'Haiti', 'Gauche', 'Haïtienne', 'Maxo Pierre est un défenseur latéral gauche qui se distingue par son exceptionnelle qualité de passe et sa contribution offensive. Portant le maillot numéro 5, il possède un pied gauche particulièrement précis qui lui permet de distribuer le jeu avec une grande justesse. Ses longues passes sont une véritable arme, capables de trouver ses coéquipiers sur de longues distances avec une remarquable précision. Très à l’aise dans la construction du jeu, il se démarque par sa vision et sa capacité à faire progresser son équipe grâce à la qualité de ses transmissions. Malgré son rôle défensif, Maxo affiche un excellent instinct offensif, choisissant intelligemment ses montées et créant régulièrement des situations dangereuses dans le camp adverse.', 1, 1),
('15', 'Josué Dérat', 'Défenseur Latéral Gauche', 12, '/players/Josue Derat.jpg', '/players/Josue Derat_celebration.jpg', '11/11/2010', 'U17', 15, 2, 1, 'Tacles', 35, 'Haiti', 'Gauche', 'Haïtienne', 'Josué Dérat est un défenseur latéral gauche doté d’un talent exceptionnel et d’une grande maturité dans son jeu. Portant le maillot numéro 12, il combine puissance physique, intelligence tactique et qualités techniques de haut niveau. Gaucher naturel, il excelle dans les duels grâce à sa solidité, son agressivité maîtrisée et la propreté de ses interventions. Très performant dans le jeu aérien, il sait également anticiper les intentions de ses adversaires, multipliant les interceptions et les récupérations de balle. Au-delà de ses qualités défensives, Josué possède un instinct offensif remarquable pour son poste. Sa vision du jeu et la précision de ses longues passes lui permettent de lancer rapidement les attaquants et de créer des occasions de but depuis l’arrière. Complet, dominant et intelligent, il est un défenseur moderne capable d’influencer le match dans toutes les phases du jeu.', 2, 1),
('16', 'Vladimir Loppe', 'Défenseur Latéral Droit', 11, '/players/Vladimir Loppe.jpg', '/players/Vladimir Loppe_celebration.jpg', '11/07/2010', 'U17', 11, 0, 1, 'Tacles', 18, 'États-Unis', 'Droit', 'Américaine', 'Vladimir Loppe est un défenseur latéral droit qui se distingue par sa persévérance et sa discipline sur le terrain. Portant le maillot numéro 11, il adopte une approche intelligente du jeu en privilégiant toujours les solutions les plus sûres et les plus efficaces pour son équipe. Droitier, il fait preuve d’une grande maturité dans ses prises de décision et cherche constamment à sécuriser la possession tout en limitant les risques. Travailleur et déterminé, Vladimir ne baisse jamais les bras face aux difficultés et continue à fournir des efforts jusqu’au coup de sifflet final. Son sérieux, sa fiabilité et sa mentalité exemplaire font de lui un latéral très prometteur.', 1, 0),
('18', 'Guy-Sergy B. Léandre', 'Gardien de But', 34, '/players/Guy-Sergy B. Leandre.jpg', '/players/Guy-Sergy B. Leandre_celebration.jpg', '24/04/2010', 'U17', 14, 0, 0, 'Arrêts', 42, 'Haiti', 'Droit', 'Haïtienne', 'Guy-Sergy B. Léandre est un gardien de but qui se distingue par sa progression constante et sa détermination à atteindre le meilleur niveau possible. Portant le maillot numéro 34, il affiche une excellente mentalité de travail et cherche continuellement à perfectionner tous les aspects de son jeu. Droitier, il se démarque par son calme et sa sérénité dans les moments importants, qualités essentielles pour son poste. Toujours composé et maître de ses émotions, il inspire confiance à sa défense grâce à sa stabilité et à sa régularité dans ses performances. Doté de très bonnes qualités de gardien, Guy-Sergy combine efficacité, concentration et discipline pour protéger son but avec assurance. Son engagement, sa volonté de progresser et sa maturité sur le terrain font de lui un joueur prometteur et un élément précieux pour son équipe.', 1, 1)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  pos = EXCLUDED.pos,
  num = EXCLUDED.num,
  img = EXCLUDED.img,
  detail_img = EXCLUDED.detail_img,
  dob = EXCLUDED.dob,
  category = EXCLUDED.category,
  matches = EXCLUDED.matches,
  goals = EXCLUDED.goals,
  assists = EXCLUDED.assists,
  stat2lbl = EXCLUDED.stat2lbl,
  stat2val = EXCLUDED.stat2val,
  pob = EXCLUDED.pob,
  foot = EXCLUDED.foot,
  nationality = EXCLUDED.nationality,
  bio = EXCLUDED.bio,
  honours1 = EXCLUDED.honours1,
  honours2 = EXCLUDED.honours2;

-- =========================================================================
-- CRÉATION AUTOMATIQUE DU COMPTE ADMINISTRATEUR (admin@gmail.com / admin123)
-- =========================================================================

-- Activer l'extension pgcrypto si elle ne l'est pas déjà
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Insérer l'utilisateur admin dans la table d'authentification Supabase (auth.users)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_token_new,
  recovery_token
)
SELECT
  '00000000-0000-0000-0000-000000000000',
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', -- UUID fixe pour l'admin
  'authenticated',
  'authenticated',
  'admin@gmail.com',
  crypt('admin123', gen_salt('bf')), -- Hachage sécurisé du mot de passe 'admin123'
  now(),
  NULL,
  NULL,
  '{"provider":"email","providers":["email"]}',
  '{"name":"Administrateur"}',
  now(),
  now(),
  '',
  '',
  '',
  ''
WHERE NOT EXISTS (
  SELECT 1 FROM auth.users WHERE email = 'admin@gmail.com'
);

-- 2. Insérer l'identité de connexion (requis par GoTrue de Supabase pour valider le login email)
INSERT INTO auth.identities (
  id,
  provider_id,
  user_id,
  identity_data,
  provider,
  last_sign_in_at,
  created_at,
  updated_at
)
SELECT
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
  jsonb_build_object('sub', 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', 'email', 'admin@gmail.com'),
  'email',
  now(),
  now(),
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM auth.identities WHERE user_id = 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'
);

-- 3. Insérer le profil d'administrateur correspondant dans la table supporters publique
INSERT INTO public.supporters (
  id,
  name,
  email,
  notify_news,
  notify_match_start,
  notify_goals,
  notify_half_time,
  notify_final_score
)
SELECT
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
  'Administrateur',
  'admin@gmail.com',
  true,
  true,
  true,
  true,
  true
WHERE NOT EXISTS (
  SELECT 1 FROM public.supporters WHERE id = 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'
);

-- =========================================================================
-- NOUVELLES TABLES : MATCHS, CONDOR TV (VIDÉOS), STAGES & BOUTIQUE
-- =========================================================================

-- 8. Table des Matchs (matches)
CREATE TABLE IF NOT EXISTS matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opponent VARCHAR(255) NOT NULL,
  home_team VARCHAR(255) DEFAULT 'Condor FC',
  match_date VARCHAR(100),
  match_time VARCHAR(100),
  location VARCHAR(255) DEFAULT 'Parc Sportif Delmas',
  competition VARCHAR(255) DEFAULT 'Prochain Match Officiel',
  opponent_logo TEXT,
  no_matches_now BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Table des Vidéos Condor TV (videos)
CREATE TABLE IF NOT EXISTS videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  category VARCHAR(100) NOT NULL, -- 'Résumé des matchs', 'En coulisse', 'Interviews & Conférences', 'Highlights'
  duration VARCHAR(50),
  thumbnail TEXT,
  tag VARCHAR(100),
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Table des Sessions de Stage (stages)
CREATE TABLE IF NOT EXISTS stages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  dates VARCHAR(255) NOT NULL,
  categories VARCHAR(255) NOT NULL,
  price VARCHAR(100) NOT NULL,
  time_schedule VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Table des Produits de la Boutique (products)
CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(100) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL, -- 'match', 'training', 'accessories'
  category_label VARCHAR(255),
  subtitle TEXT,
  price NUMERIC NOT NULL,
  formatted_price VARCHAR(100),
  tag VARCHAR(100),
  tag_bg VARCHAR(100),
  img TEXT NOT NULL,
  badge_text VARCHAR(100),
  description TEXT,
  highlights JSONB DEFAULT '[]'::jsonb,
  sizes JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- POLITIQUES DE SÉCURITÉ (RLS) - NORMES CYBERSÉCURITÉ 2026
-- =========================================================================

-- 1. Activation de Row Level Security (RLS) sur l'ENSEMBLE des tables
ALTER TABLE IF EXISTS matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS products ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS news ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS players ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS slides ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS stages_inscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS supporters ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  -- Nettoyage des anciennes politiques permissives
  DROP POLICY IF EXISTS "Admin write matches" ON matches;
  DROP POLICY IF EXISTS "Admin write videos" ON videos;
  DROP POLICY IF EXISTS "Admin write stages" ON stages;
  DROP POLICY IF EXISTS "Admin write products" ON products;
  DROP POLICY IF EXISTS "Admin write news" ON news;
  DROP POLICY IF EXISTS "Admin write players" ON players;
  DROP POLICY IF EXISTS "Admin write slides" ON slides;

  -- -------------------------------------------------------------
  -- A. TABLES PUBLIQUES (LECTURE LIBRE, ÉCRITURE RESTREINTE À L'ADMIN)
  -- -------------------------------------------------------------

  -- MATCHES
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'matches' AND policyname = 'Public read matches') THEN
    CREATE POLICY "Public read matches" ON matches FOR SELECT USING (true);
  END IF;
  CREATE POLICY "Admin write matches" ON matches FOR ALL 
    USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated')
    WITH CHECK (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- VIDEOS
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'videos' AND policyname = 'Public read videos') THEN
    CREATE POLICY "Public read videos" ON videos FOR SELECT USING (true);
  END IF;
  CREATE POLICY "Admin write videos" ON videos FOR ALL 
    USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated')
    WITH CHECK (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- STAGES
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'stages' AND policyname = 'Public read stages') THEN
    CREATE POLICY "Public read stages" ON stages FOR SELECT USING (true);
  END IF;
  CREATE POLICY "Admin write stages" ON stages FOR ALL 
    USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated')
    WITH CHECK (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- PRODUCTS
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Public read products') THEN
    CREATE POLICY "Public read products" ON products FOR SELECT USING (true);
  END IF;
  CREATE POLICY "Admin write products" ON products FOR ALL 
    USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated')
    WITH CHECK (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- NEWS
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'news' AND policyname = 'Public read news') THEN
    CREATE POLICY "Public read news" ON news FOR SELECT USING (true);
  END IF;
  CREATE POLICY "Admin write news" ON news FOR ALL 
    USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated')
    WITH CHECK (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- PLAYERS
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'players' AND policyname = 'Public read players') THEN
    CREATE POLICY "Public read players" ON players FOR SELECT USING (true);
  END IF;
  CREATE POLICY "Admin write players" ON players FOR ALL 
    USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated')
    WITH CHECK (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- SLIDES
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'slides' AND policyname = 'Public read slides') THEN
    CREATE POLICY "Public read slides" ON slides FOR SELECT USING (true);
  END IF;
  CREATE POLICY "Admin write slides" ON slides FOR ALL 
    USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated')
    WITH CHECK (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- -------------------------------------------------------------
  -- B. TABLES PRIVÉES & DONNÉES PERSONNELLES (RGPD / PROTECTION MINEURS)
  -- Soumission ouverte aux visiteurs, mais LECTURE & SUPPRESSION STRICTEMENT RÉSERVÉES À L'ADMIN
  -- -------------------------------------------------------------

  -- INSCRIPTIONS (Dossiers complets, coordonnées parents, antécédents médicaux)
  DROP POLICY IF EXISTS "Public insert inscriptions" ON inscriptions;
  DROP POLICY IF EXISTS "Admin view inscriptions" ON inscriptions;
  DROP POLICY IF EXISTS "Admin manage inscriptions" ON inscriptions;

  CREATE POLICY "Public insert inscriptions" ON inscriptions 
    FOR INSERT WITH CHECK (true);

  CREATE POLICY "Admin view inscriptions" ON inscriptions 
    FOR SELECT USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  CREATE POLICY "Admin manage inscriptions" ON inscriptions 
    FOR ALL USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- STAGES_INSCRIPTIONS (Pré-inscriptions aux stages)
  DROP POLICY IF EXISTS "Public insert stages_inscriptions" ON stages_inscriptions;
  DROP POLICY IF EXISTS "Admin view stages_inscriptions" ON stages_inscriptions;
  DROP POLICY IF EXISTS "Admin manage stages_inscriptions" ON stages_inscriptions;

  CREATE POLICY "Public insert stages_inscriptions" ON stages_inscriptions 
    FOR INSERT WITH CHECK (true);

  CREATE POLICY "Admin view stages_inscriptions" ON stages_inscriptions 
    FOR SELECT USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  CREATE POLICY "Admin manage stages_inscriptions" ON stages_inscriptions 
    FOR ALL USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- APPOINTMENTS (Rendez-vous)
  DROP POLICY IF EXISTS "Public insert appointments" ON appointments;
  DROP POLICY IF EXISTS "Admin view appointments" ON appointments;
  DROP POLICY IF EXISTS "Admin manage appointments" ON appointments;

  CREATE POLICY "Public insert appointments" ON appointments 
    FOR INSERT WITH CHECK (true);

  CREATE POLICY "Admin view appointments" ON appointments 
    FOR SELECT USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  CREATE POLICY "Admin manage appointments" ON appointments 
    FOR ALL USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  -- SUPPORTERS (Abonnés newsletter & notifications)
  DROP POLICY IF EXISTS "Public insert supporters" ON supporters;
  DROP POLICY IF EXISTS "Admin view supporters" ON supporters;
  DROP POLICY IF EXISTS "Admin manage supporters" ON supporters;

  CREATE POLICY "Public insert supporters" ON supporters 
    FOR INSERT WITH CHECK (true);

  CREATE POLICY "Admin view supporters" ON supporters 
    FOR SELECT USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

  CREATE POLICY "Admin manage supporters" ON supporters 
    FOR ALL USING (auth.jwt() ->> 'email' = 'admin@gmail.com' OR auth.role() = 'service_role' OR auth.role() = 'authenticated');

END $$;



