-- SCRIPT DE CRÉATION DES TABLES POUR SUPABASE (A EXECUTER DANS LE SQL EDITOR DE SUPABASE)

-- 1. Table actualités (news)
CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cat VARCHAR(100) NOT NULL,
  date VARCHAR(100) NOT NULL,
  title TEXT NOT NULL,
  desc_text TEXT NOT NULL,
  img TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table joueurs (players)
CREATE TABLE IF NOT EXISTS players (
  id VARCHAR(100) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  pos VARCHAR(100) NOT NULL,
  num INT NOT NULL,
  img TEXT NOT NULL,
  filter VARCHAR(100) DEFAULT 'none',
  dob VARCHAR(100) NOT NULL,
  category VARCHAR(100) NOT NULL,
  height VARCHAR(100),
  weight VARCHAR(100),
  matches INT DEFAULT 0,
  goals INT DEFAULT 0,
  assists INT DEFAULT 0,
  stat2lbl VARCHAR(100) DEFAULT 'Buts',
  stat2val INT DEFAULT 0,
  pob VARCHAR(255) DEFAULT 'Port-au-Prince, Haïti',
  foot VARCHAR(50) DEFAULT 'Droit',
  nationality VARCHAR(100) DEFAULT 'Haïtienne',
  bio TEXT,
  honours1 INT DEFAULT 1,
  honours2 INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table des images du slider (slides)
CREATE TABLE IF NOT EXISTS slides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Table inscriptions aux stages (stages_inscriptions)
CREATE TABLE IF NOT EXISTS stages_inscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL,
  dob VARCHAR(100) NOT NULL,
  tel VARCHAR(100) NOT NULL,
  stage TEXT NOT NULL,
  note TEXT,
  photo TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table rendez-vous administratifs (appointments)
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_nom VARCHAR(255) NOT NULL,
  enfant_nom VARCHAR(255) NOT NULL,
  tel VARCHAR(100) NOT NULL,
  date VARCHAR(100) NOT NULL,
  heure VARCHAR(100) NOT NULL,
  raison VARCHAR(255) DEFAULT 'Inscription académique',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Table profils supporters (supporters)
CREATE TABLE IF NOT EXISTS supporters (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  notify_news BOOLEAN DEFAULT TRUE,
  notify_match_start BOOLEAN DEFAULT TRUE,
  notify_goals BOOLEAN DEFAULT TRUE,
  notify_half_time BOOLEAN DEFAULT TRUE,
  notify_final_score BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Table des inscriptions complètes (inscriptions)
CREATE TABLE IF NOT EXISTS inscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enfant_nom VARCHAR(255) NOT NULL,
  enfant_prenom VARCHAR(255) NOT NULL,
  enfant_dob VARCHAR(100) NOT NULL,
  parent_nom VARCHAR(255) NOT NULL,
  parent_prenom VARCHAR(255) NOT NULL,
  parent_tel VARCHAR(100) NOT NULL,
  parent_email VARCHAR(255) NOT NULL,
  form_data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- INSERER LES DONNEES INITIALES (EXEMPLES)

-- Insérer les slides par défaut
INSERT INTO slides (url) VALUES
('/stadium_hero_1780681869623.png'),
('/club_hero.png'),
('/kick_hero.png'),
('/news_hero.png'),
('/trophy_moment_1780681956500.png'),
('/soccer.png'),
('/universe_bg.png');

-- Insérer les actualités par défaut
INSERT INTO news (cat, date, title, desc_text, img) VALUES
('Match', 'Il y a 2 heures', 'Le Condor FC décroche une victoire cruciale à l''extérieur', 'Une performance époustouflante en seconde période assure les trois points sur la route.', '/player_action_1_1780681882713.png'),
('Transferts', 'Il y a 5 heures', 'Nouvelle recrue officiellement dévoilée à l''Arène', 'Le club renforce sa ligne offensive avec l''arrivée d''un jeune international prometteur.', '/condor_jersey_1780681923538.png');

-- Insérer les joueurs
INSERT INTO players (id, name, pos, num, img, dob, category, height, weight, matches, goals, assists, stat2lbl, stat2val, pob, foot, nationality, bio, honours1, honours2) VALUES
('1', 'Ernesto Guivens', 'Gardien de but', 1, '/players/Ernesto Guivens.jpg', '12 Mai 2009', 'Équipe Première', '1.82m', '72kg', 12, 0, 0, 'Arrêts', 45, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Gardien agile formé au club.', 2, 1),
('2', 'Serdgy Leandre', 'Gardien de but', 2, '/players/Serdgy Leandre.jpg', '05 Avril 2009', 'Équipe Première', '1.74m', '65kg', 14, 0, 0, 'Arrêts', 48, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Jeune gardien dynamique formé au club.', 1, 1),
('3', 'Steevenson Thermidor', 'Arrière Gauche', 3, '/players/Steevenson Thermidor.jpg', '18 Novembre 2009', 'Équipe Première', '1.71m', '62kg', 13, 0, 4, 'Tacles', 22, 'Delmas, Haïti', 'Gauche', 'Haïtienne', 'Latéral gauche technique apportant beaucoup offensivement.', 1, 1),
('4', 'Josue Derat', 'Défenseur Central', 4, '/players/Josue Derat.jpg', '22 Février 2009', 'Équipe Première', '1.85m', '78kg', 15, 2, 1, 'Tacles', 35, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Roc de la défense centrale, excellent dans le jeu aérien.', 2, 1),
('5', 'Maxo Pierre', 'Défenseur Central', 5, '/players/Maxo Pierre.jpg', '10 Septembre 2009', 'U17', '1.80m', '75kg', 14, 1, 0, 'Tacles', 31, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Solide défenseur central U17.', 1, 1),
('6', 'Marc-Hero Clerissier', 'Milieu Central', 6, '/players/Marc-Hero Clerissier.jpg', '14 Janvier 2009', 'U17', '1.76m', '68kg', 15, 3, 5, 'Buts', 3, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Meneur de jeu avec une excellente vision périphérique.', 2, 2),
('7', 'Rivaldo Sanon', 'Ailier Gauche', 7, '/players/Rivaldo Sanon.jpg', '30 Juin 2009', 'U17', '1.73m', '64kg', 14, 8, 6, 'Buts', 8, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Ailier percutant et grand buteur de l''équipe U17.', 2, 1),
('8', 'Smarthinly Berry', 'Milieu Défensif', 8, '/players/Smarthinly Berry.jpg', '02 Juillet 2009', 'U17', '1.78m', '70kg', 13, 1, 2, 'Tacles', 26, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Récupérateur infatigable devant la défense.', 1, 1),
('9', 'Jameslay Nelson', 'Avant-Centre', 9, '/players/Jameslay Nelson.jpg', '11 Décembre 2009', 'U15', '1.81m', '74kg', 15, 12, 4, 'Buts', 12, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Attaquant clinique devant le but.', 2, 2),
('10', 'Wilbensly Laforsse', 'Gardien de but', 10, '/players/Wilbensly Laforsse.jpg', '25 Août 2009', 'U15', '1.72m', '63kg', 14, 0, 0, 'Arrêts', 35, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Jeune gardien appliqué formé au club.', 2, 1),
('11', 'Messi Frederic', 'Ailier Droit', 11, '/players/Messi Frederic.jpg', '24 Octobre 2009', 'U15', '1.69m', '59kg', 15, 10, 7, 'Buts', 10, 'Delmas, Haïti', 'Gauche', 'Haïtienne', 'Ailier vif et excellent passeur.', 2, 2),
('12', 'Vladimir Loppe', 'Défenseur Central', 12, '/players/Vladimir Loppe.jpg', '03 Mars 2009', 'U15', '1.79m', '73kg', 11, 0, 1, 'Tacles', 18, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Défenseur appliqué et rigoureux.', 1, 0),
('14', 'Wildens Joseph', 'Milieu Central', 14, '/players/Wildens Joseph.jpg', '17 Juillet 2009', 'U13', '1.75m', '67kg', 12, 2, 2, 'Buts', 2, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Milieu dynamique de la catégorie U13.', 1, 1),
('15', 'Widley Fleurius', 'Milieu Central', 15, '/players/Widley Fleurius.jpg', '09 Mai 2009', 'U13', '1.77m', '69kg', 13, 1, 4, 'Buts', 1, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Milieu relayeur très travailleur.', 1, 1),
('16', 'Teddy Alexandre', 'Gardien de but', 16, '/players/Teddy Alexandre.jpg', '28 Janvier 2009', 'U13', '1.84m', '76kg', 4, 0, 0, 'Arrêts', 12, 'Delmas, Haïti', 'Droit', 'Haïtienne', 'Jeune gardien plein de promesses.', 1, 0);

-- =========================================================================
-- CRÉATION AUTOMATIQUE DU COMPTE ADMINISTRATEUR (admin@gmail.com / admin123)
-- =========================================================================

-- Activer l'extension pgcrypto si elle ne l'est pas déjà
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Insérer l'utilisateur admin dans la table d'authentification Supabase (auth.users)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_token_new,
  recovery_token
)
SELECT
  '00000000-0000-0000-0000-000000000000',
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', -- UUID fixe pour l'admin
  'authenticated',
  'authenticated',
  'admin@gmail.com',
  crypt('admin123', gen_salt('bf')), -- Hachage sécurisé du mot de passe 'admin123'
  now(),
  NULL,
  NULL,
  '{"provider":"email","providers":["email"]}',
  '{"name":"Administrateur"}',
  now(),
  now(),
  '',
  '',
  '',
  ''
WHERE NOT EXISTS (
  SELECT 1 FROM auth.users WHERE email = 'admin@gmail.com'
);

-- 2. Insérer l'identité de connexion (requis par GoTrue de Supabase pour valider le login email)
INSERT INTO auth.identities (
  id,
  provider_id,
  user_id,
  identity_data,
  provider,
  last_sign_in_at,
  created_at,
  updated_at
)
SELECT
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
  jsonb_build_object('sub', 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d', 'email', 'admin@gmail.com'),
  'email',
  now(),
  now(),
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM auth.identities WHERE user_id = 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'
);

-- 3. Insérer le profil d'administrateur correspondant dans la table supporters publique
INSERT INTO public.supporters (
  id,
  name,
  email,
  notify_news,
  notify_match_start,
  notify_goals,
  notify_half_time,
  notify_final_score
)
SELECT
  'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
  'Administrateur',
  'admin@gmail.com',
  true,
  true,
  true,
  true,
  true
WHERE NOT EXISTS (
  SELECT 1 FROM public.supporters WHERE id = 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'
);

